version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: yosoyPostgres
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db_network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: yopegeadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: correo@correo.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    networks:
      - db_network
    restart: unless-stopped
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  db_network:
    driver: bridge